# Generated by Django 3.0.8 on 2020-11-28 14:00

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('taksist', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='taxicategory',
            name='test',
        ),
    ]
