# Generated by Django 3.0.8 on 2020-11-28 14:01

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('taksist', '0002_remove_taxicategory_test'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='taxicategory',
            name='id',
        ),
        migrations.RemoveField(
            model_name='taxistatus',
            name='id',
        ),
        migrations.AddField(
            model_name='taxicategory',
            name='user_id',
            field=models.OneToOneField(default=1, on_delete=django.db.models.deletion.CASCADE, primary_key=True, serialize=False, to=settings.AUTH_USER_MODEL),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='taxistatus',
            name='user_id',
            field=models.OneToOneField(default=1, on_delete=django.db.models.deletion.CASCADE, primary_key=True, serialize=False, to=settings.AUTH_USER_MODEL),
            preserve_default=False,
        ),
    ]
