# Generated by Django 3.0.8 on 2020-11-28 14:38

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('taksist', '0003_auto_20201128_0601'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='taxistatus',
            name='user_id',
        ),
        migrations.DeleteModel(
            name='TaxiCategory',
        ),
        migrations.DeleteModel(
            name='TaxiStatus',
        ),
    ]
