# Generated by Django 3.0.8 on 2020-11-28 14:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('taksist', '0004_auto_20201128_0638'),
    ]

    operations = [
        migrations.CreateModel(
            name='TaxiCategory',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(choices=[('saher_ara', 'Şäher ara gatnaýaryn.'), ('saher_ici', 'Diňe şäher içinde işleýärin.'), ('saher_obalary', 'Bir şäheriň ýada etrabyň obalarynyň arasynda gatnaýaryn.')], max_length=255)),
            ],
        ),
        migrations.CreateModel(
            name='TaxiStatus',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('status', models.CharField(choices=[('isde', 'Işe çykdym, işläp ýörün.'), ('dyncda', 'Şu wagt işlämok, dynç alýaryn.')], max_length=10)),
            ],
        ),
    ]
