# Generated by Django 3.0.8 on 2020-11-29 07:45

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('taksist', '0008_auto_20201128_2340'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='taxiprofile',
            name='category',
        ),
        migrations.RemoveField(
            model_name='taxiprofile',
            name='status',
        ),
    ]
