# Generated by Django 3.0.8 on 2020-11-29 08:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('taksist', '0012_auto_20201128_2357'),
    ]

    operations = [
        migrations.AddField(
            model_name='taxiprofile',
            name='mobile',
            field=models.IntegerField(default=65656565),
            preserve_default=False,
        ),
    ]
