# Generated by Django 3.0.8 on 2020-11-29 17:14

from django.db import migrations
import django_resized.forms


class Migration(migrations.Migration):

    dependencies = [
        ('taksist', '0016_auto_20201129_0840'),
    ]

    operations = [
        migrations.AlterField(
            model_name='taxiprofile',
            name='car_photo',
            field=django_resized.forms.ResizedImageField(blank=True, crop=None, default='car_photo/default_car.png', force_format=None, keep_meta=True, quality=75, size=[100, 100], upload_to='car_photos/'),
        ),
        migrations.AlterField(
            model_name='taxiprofile',
            name='user_photo',
            field=django_resized.forms.ResizedImageField(blank=True, crop=None, default='user_photo/default_taksist.png', force_format=None, keep_meta=True, quality=75, size=[100, 100], upload_to='user_photos/'),
        ),
    ]
