# Generated by Django 3.1.7 on 2021-03-06 13:21

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('taksist', '0021_auto_20210304_2213'),
    ]

    operations = [
        migrations.CreateModel(
            name='EtrapObalary',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('city', models.CharField(choices=[(1, 'Sarahs'), (2, 'Mary'), (3, 'Balkanabat'), (4, 'Tejen'), (5, 'Aşgabat'), (6, 'Daşoguz'), (7, 'Çärjew')], max_length=20)),
                ('user_id', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='SaherAra',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('city1', models.CharField(choices=[(1, 'Sarahs'), (2, 'Mary'), (3, 'Balkanabat'), (4, 'Tejen'), (5, 'Aşgabat'), (6, 'Daşoguz'), (7, 'Çärjew')], max_length=20)),
                ('city2', models.CharField(choices=[(1, 'Sarahs'), (2, 'Mary'), (3, 'Balkanabat'), (4, 'Tejen'), (5, 'Aşgabat'), (6, 'Daşoguz'), (7, 'Çärjew')], max_length=20)),
                ('user_id', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='SaherIci',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('city', models.CharField(choices=[(1, 'Sarahs'), (2, 'Mary'), (3, 'Balkanabat'), (4, 'Tejen'), (5, 'Aşgabat'), (6, 'Daşoguz'), (7, 'Çärjew')], max_length=20)),
                ('user_id', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.AddField(
            model_name='taxiprofile',
            name='cat_id',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='taksist.category'),
        ),
        migrations.DeleteModel(
            name='Route',
        ),
    ]
