# Generated by Django 2.2 on 2021-03-27 04:37

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('taksist', '0025_auto_20210325_1355'),
    ]

    operations = [
        migrations.AlterField(
            model_name='etrapobalary',
            name='user_id',
            field=models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='haysy_etrap', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AlterField(
            model_name='saherici',
            name='user_id',
            field=models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='haysy_saher', to=settings.AUTH_USER_MODEL),
        ),
    ]
