# Generated by Django 2.2 on 2021-03-27 11:01

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('taksist', '0026_auto_20210327_0937'),
    ]

    operations = [
        migrations.AddField(
            model_name='etrapobalary',
            name='taxi_id',
            field=models.OneToOneField(null=True, on_delete=django.db.models.deletion.CASCADE, to='taksist.TaxiProfile'),
        ),
        migrations.AddField(
            model_name='saherara',
            name='taxi_id',
            field=models.OneToOneField(null=True, on_delete=django.db.models.deletion.CASCADE, to='taksist.TaxiProfile'),
        ),
        migrations.AddField(
            model_name='saherici',
            name='taxi_id',
            field=models.OneToOneField(null=True, on_delete=django.db.models.deletion.CASCADE, to='taksist.TaxiProfile'),
        ),
    ]
