# Generated by Django 2.2 on 2021-06-28 12:04

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('taksist', '0029_auto_20210628_1657'),
    ]

    operations = [
        migrations.AddField(
            model_name='taxiprofile',
            name='nira',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='nira1', to='taksist.City'),
        ),
        migrations.AddField(
            model_name='taxiprofile',
            name='nireden',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='nireden1', to='taksist.City'),
        ),
    ]
