# Generated by Django 2.2 on 2021-06-29 09:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('taksist', '0030_auto_20210628_1704'),
    ]

    operations = [
        migrations.AddField(
            model_name='taxiprofile',
            name='category',
            field=models.IntegerField(choices=[(1, 'Şäher Içi'), (2, 'Etrap Obalary'), (3, 'Şäher Ara')], null=True),
        ),
        migrations.AddField(
            model_name='taxiprofile',
            name='status',
            field=models.IntegerField(choices=[(0, 'Dynçda'), (1, 'Işde')], null=True),
        ),
    ]
