# Generated by Django 2.2 on 2021-06-29 11:02

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('taksist', '0031_auto_20210629_1431'),
    ]

    operations = [
        migrations.AlterField(
            model_name='taxiprofile',
            name='nira',
            field=models.ForeignKey(choices=[(1, 'Şäher Içi'), (2, 'Etrap Obalary'), (8, 'Tejen'), (9, 'Kerki'), (10, 'Balkanabat'), (11, 'Aşgabat'), (12, 'Mary'), (13, 'Sarahs'), (14, 'Türkmenabat'), (15, 'Daşoguz')], null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='nira1', to='taksist.City'),
        ),
        migrations.AlterField(
            model_name='taxiprofile',
            name='nireden',
            field=models.ForeignKey(choices=[(1, 'Şäher Içi'), (2, 'Etrap Obalary'), (8, 'Tejen'), (9, 'Kerki'), (10, 'Balkanabat'), (11, 'Aşgabat'), (12, 'Mary'), (13, 'Sarahs'), (14, 'Türkmenabat'), (15, 'Daşoguz')], null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='nireden1', to='taksist.City'),
        ),
    ]
