# Generated by Django 2.2 on 2021-06-29 11:05

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('taksist', '0032_auto_20210629_1602'),
    ]

    operations = [
        migrations.AlterField(
            model_name='taxiprofile',
            name='nira',
            field=models.ForeignKey(choices=[(1, 'Asgabat'), (2, 'Sarahs')], null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='nira1', to='taksist.City'),
        ),
        migrations.AlterField(
            model_name='taxiprofile',
            name='nireden',
            field=models.ForeignKey(choices=[(1, 'Asgabat'), (2, 'Sarahs')], null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='nireden1', to='taksist.City'),
        ),
    ]
