# Generated by Django 2.2 on 2021-06-29 13:47

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('taksist', '0034_auto_20210629_1639'),
    ]

    operations = [
        migrations.AlterField(
            model_name='taxiprofile',
            name='nira',
            field=models.ForeignKey(blank=True, choices=[('Şäher Içi', 'Şäher Içi'), ('Etrap Obalary', 'Etrap Obalary'), ('Tejen', 'Tejen'), ('Kerki', 'Kerki'), ('Balkanabat', 'Balkanabat'), ('Aşgabat', 'Aşgabat'), ('Mary', 'Mary'), ('Sarahs', 'Sarahs'), ('Türkmenabat', 'Türkmenabat'), ('Daşoguz', 'Daşoguz')], null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='nira1', to='taksist.City'),
        ),
        migrations.AlterField(
            model_name='taxiprofile',
            name='nireden',
            field=models.ForeignKey(blank=True, choices=[('Tejen', 'Tejen'), ('Kerki', 'Kerki'), ('Balkanabat', 'Balkanabat'), ('Aşgabat', 'Aşgabat'), ('Mary', 'Mary'), ('Sarahs', 'Sarahs'), ('Türkmenabat', 'Türkmenabat'), ('Daşoguz', 'Daşoguz')], null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='nireden1', to='taksist.City'),
        ),
    ]
