# Generated by Django 3.2.5 on 2021-07-29 12:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('taksist', '0036_auto_20210629_2004'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='saherara',
            name='city1',
        ),
        migrations.RemoveField(
            model_name='saherara',
            name='city2',
        ),
        migrations.RemoveField(
            model_name='saherara',
            name='taxi_id',
        ),
        migrations.RemoveField(
            model_name='saherara',
            name='user_id',
        ),
        migrations.RemoveField(
            model_name='saherici',
            name='taxi_id',
        ),
        migrations.RemoveField(
            model_name='saherici',
            name='user_id',
        ),
        migrations.RemoveField(
            model_name='taxicategory',
            name='user_id',
        ),
        migrations.RemoveField(
            model_name='taxistatus',
            name='user_id',
        ),
        migrations.AlterField(
            model_name='category',
            name='id',
            field=models.AutoField(primary_key=True, serialize=False),
        ),
        migrations.AlterField(
            model_name='city',
            name='id',
            field=models.AutoField(primary_key=True, serialize=False),
        ),
        migrations.AlterField(
            model_name='status',
            name='id',
            field=models.AutoField(primary_key=True, serialize=False),
        ),
        migrations.DeleteModel(
            name='EtrapObalary',
        ),
        migrations.DeleteModel(
            name='SaherAra',
        ),
        migrations.DeleteModel(
            name='SaherIci',
        ),
        migrations.DeleteModel(
            name='TaxiCategory',
        ),
        migrations.DeleteModel(
            name='TaxiStatus',
        ),
    ]
