# Generated by Django 3.0.8 on 2020-11-28 13:56

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion
import taksist.utils


class Migration(migrations.Migration):

    initial = True

    # dependencies = [
    #     ('auth', '0011_update_proxy_permissions'),
    # ]

    operations = [
        migrations.CreateModel(
            name='TaxiCategory',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(choices=[('saher_ara', 'Şäher ara gatnaýaryn.'), ('saher_ici', 'Diňe şäher içinde işleýärin.'), ('saher_obalary', 'Bir şäheriň ýada etrabyň obalarynyň arasynda gatnaýaryn.')], max_length=255)),
                ('test', models.CharField(max_length=111)),
            ],
        ),
        migrations.CreateModel(
            name='TaxiProfile',
            fields=[
                ('user_id', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, primary_key=True, serialize=False, to=settings.AUTH_USER_MODEL)),
                ('car_photo', models.ImageField(upload_to=taksist.utils.user_photo_upload_path)),
                ('user_photo', models.ImageField(upload_to=taksist.utils.car_photo_upload_path)),
            ],
        ),
        migrations.CreateModel(
            name='TaxiStatus',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('status', models.CharField(choices=[('isde', 'Işe çykdym, işläp ýörün.'), ('dyncda', 'Şu wagt işlämok, dynç alýaryn.')], max_length=10)),
            ],
        ),
    ]
