# Generated by Django 3.2.5 on 2021-07-30 12:16

from django.db import migrations, models
import django.db.models.deletion
import django_resized.forms


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('auth', '0012_alter_user_first_name_max_length'),
    ]

    operations = [
        migrations.CreateModel(
            name='Category',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('name', models.CharField(max_length=20)),
            ],
        ),
        migrations.CreateModel(
            name='City',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('name', models.CharField(max_length=20)),
            ],
        ),
        migrations.CreateModel(
            name='Status',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('name', models.CharField(max_length=30)),
            ],
        ),
        migrations.CreateModel(
            name='TaxiProfile',
            fields=[
                ('user_id', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, primary_key=True, serialize=False, to='auth.user')),
                ('mobile', models.CharField(max_length=13)),
                ('car_photo', django_resized.forms.ResizedImageField(blank=True, crop=None, default='car_photo/default_car.png', force_format=None, keep_meta=True, quality=75, size=[100, 100], upload_to='car_photos/')),
                ('user_photo', django_resized.forms.ResizedImageField(blank=True, crop=None, default='user_photo/default_taksist.png', force_format=None, keep_meta=True, quality=75, size=[100, 100], upload_to='user_photos/')),
                ('category', models.ForeignKey(blank=True, choices=[], null=True, on_delete=django.db.models.deletion.SET_NULL, to='taksist.category')),
                ('nira', models.ForeignKey(blank=True, choices=[], null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='nira1', to='taksist.city')),
                ('nireden', models.ForeignKey(blank=True, choices=[], null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='nireden1', to='taksist.city')),
                ('status', models.ForeignKey(blank=True, choices=[], null=True, on_delete=django.db.models.deletion.SET_NULL, to='taksist.status')),
            ],
        ),
    ]
