# Generated by Django 3.2.5 on 2021-07-30 13:05

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('taksist', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='taxiprofile',
            name='category',
            field=models.ForeignKey(blank=True, choices=[(1, 'Şäher Içi'), (2, 'Etrap Obalary'), (3, 'Şäher Ara')], null=True, on_delete=django.db.models.deletion.SET_NULL, to='taksist.category'),
        ),
    ]
