# Generated by Django 3.2.6 on 2021-09-17 09:29

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('taksist', '0002_auto_20210917_1412'),
    ]

    operations = [
        migrations.AddField(
            model_name='taxiprofile',
            name='test',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_query_name='test', to='taksist.status'),
        ),
        migrations.AlterField(
            model_name='taxiprofile',
            name='status',
            field=models.ForeignKey(blank=True, choices=[(1, 'Dynçda'), (2, 'Işde')], null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='test2', to='taksist.status'),
        ),
    ]
