# Generated by Django 3.2.6 on 2021-09-26 13:56

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('taksist', '0004_auto_20210921_1209'),
    ]

    operations = [
        migrations.RenameField(
            model_name='taxiprofile',
            old_name='user_id',
            new_name='user',
        ),
    ]
