# Generated by Django 3.0.8 on 2020-11-28 15:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('taksist', '0005_taxicategory_taxistatus'),
    ]

    operations = [
        migrations.AddField(
            model_name='taxiprofile',
            name='category',
            field=models.CharField(choices=[('saher_ara', 'Şäher ara gatnaýaryn.'), ('saher_ici', 'Diňe şäher içinde işleýärin.'), ('saher_obalary', 'Bir şäheriň ýada etrabyň obalarynyň arasynda gatnaýaryn.')], default='-', max_length=255),
        ),
        migrations.AddField(
            model_name='taxiprofile',
            name='status',
            field=models.CharField(choices=[('isde', 'Işe çykdym, işläp ýörün.'), ('dyncda', 'Şu wagt işlämok, dynç alýaryn.')], default='-', max_length=10),
        ),
    ]
