# Generated by Django 3.0.8 on 2020-11-29 07:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('taksist', '0009_auto_20201128_2345'),
    ]

    operations = [
        migrations.AlterField(
            model_name='taxicategory',
            name='name',
            field=models.CharField(choices=[('Şäher Arasy', 'Şäher ara gatnaýaryn.'), ('Şäher Içi', 'Diňe şäher içinde işleýärin.'), ('Etrap Obalary', 'Etrabyň obalaryna gatnaýaryn.')], max_length=255),
        ),
        migrations.AlterField(
            model_name='taxistatus',
            name='status',
            field=models.CharField(choices=[('Işde', 'Işe çykdym, işläp ýörün.'), ('Dynçda', 'Şu wagt işlämok, dynç alýaryn.')], max_length=10),
        ),
    ]
