# Generated by Django 3.0.8 on 2020-11-29 08:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('taksist', '0013_taxiprofile_mobile'),
    ]

    operations = [
        migrations.AlterField(
            model_name='taxiprofile',
            name='mobile',
            field=models.CharField(max_length=13),
        ),
    ]
