# Generated by Django 3.0.8 on 2020-11-29 08:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('taksist', '0014_auto_20201129_0023'),
    ]

    operations = [
        migrations.AlterField(
            model_name='taxicategory',
            name='name',
            field=models.CharField(choices=[('Saýlanmadyk', 'Taksistlik edýän ýeriňizi saýlaň.'), ('Şäher Arasy', 'Şäher ara gatnaýaryn.'), ('Şäher Içi', 'Diňe şäher içinde işleýärin.'), ('Etrap Obalary', 'Etrabyň obalaryna gatnaýaryn.')], max_length=255),
        ),
        migrations.AlterField(
            model_name='taxistatus',
            name='status',
            field=models.CharField(choices=[('Saýlanmadyk', 'Iş ýagaýyňyzy saýlaň.'), ('Işde', 'Işe çykdym, işläp ýörün.'), ('Dynçda', 'Şu wagt işlämok, dynç alýaryn.')], max_length=50),
        ),
    ]
