# Generated by Django 2.1.1 on 2021-01-31 15:59

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('taksist', '0018_auto_20201208_1003'),
    ]

    operations = [
        migrations.AlterField(
            model_name='taxicategory',
            name='user_id',
            field=models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='name', to=settings.AUTH_USER_MODEL),
        ),
    ]
