# Generated by Django 2.2 on 2021-03-24 11:06

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('taksist', '0023_auto_20210306_2001'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='saherara',
            name='city2',
        ),
        migrations.AlterField(
            model_name='saherara',
            name='city1',
            field=models.ForeignKey(choices=[(1, 'Sarahs'), (2, 'Mary'), (3, 'Balkanabat'), (4, 'Tejen'), (5, 'Aşgabat'), (6, 'Daşoguz'), (7, 'Çärjew')], on_delete=django.db.models.deletion.CASCADE, to='taksist.City'),
        ),
    ]
