# Generated by Django 2.2 on 2021-06-28 11:57

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('taksist', '0028_auto_20210327_1608'),
    ]

    operations = [
        migrations.AlterField(
            model_name='etrapobalary',
            name='city',
            field=models.CharField(choices=[(1, 'Şäher Içi'), (2, 'Etrap Obalary'), (8, 'Tejen'), (9, 'Kerki'), (10, 'Balkanabat'), (11, 'Aşgabat'), (12, 'Mary'), (13, 'Sarahs'), (14, 'Türkmenabat'), (15, 'Daşoguz')], max_length=20),
        ),
        migrations.AlterField(
            model_name='saherara',
            name='city1',
            field=models.ForeignKey(choices=[(1, 'Şäher Içi'), (2, 'Etrap Obalary'), (8, 'Tejen'), (9, 'Kerki'), (10, 'Balkanabat'), (11, 'Aşgabat'), (12, 'Mary'), (13, 'Sarahs'), (14, 'Türkmenabat'), (15, 'Daşoguz')], on_delete=django.db.models.deletion.CASCADE, related_name='nireden', to='taksist.City'),
        ),
        migrations.AlterField(
            model_name='saherara',
            name='city2',
            field=models.ForeignKey(choices=[(1, 'Şäher Içi'), (2, 'Etrap Obalary'), (8, 'Tejen'), (9, 'Kerki'), (10, 'Balkanabat'), (11, 'Aşgabat'), (12, 'Mary'), (13, 'Sarahs'), (14, 'Türkmenabat'), (15, 'Daşoguz')], on_delete=django.db.models.deletion.CASCADE, related_name='nira', to='taksist.City'),
        ),
        migrations.AlterField(
            model_name='saherici',
            name='city',
            field=models.CharField(choices=[(1, 'Şäher Içi'), (2, 'Etrap Obalary'), (8, 'Tejen'), (9, 'Kerki'), (10, 'Balkanabat'), (11, 'Aşgabat'), (12, 'Mary'), (13, 'Sarahs'), (14, 'Türkmenabat'), (15, 'Daşoguz')], max_length=20),
        ),
    ]
